# Change these first
owner: ranapnea # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: LifeSystem
    url: http://life-system.app/
  - name: TimeStack
    url: https://timestack.cc
  - name: EasyBp
    url: https://easybp.app
  - name: Mindly
    url: https://www.mindlyapp.com

status-website:
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Personal Upptime
  introTitle: "Using **Upptime** to monitor some sites."
  introMessage: This status page which uses **real-time** data from our [GitHub repository](https://github.com/ranapnea/upptime). 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  uptime: "*/15 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
